apiVersion: apps/v1
kind: Deployment
metadata:
  name: rustdesk-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rustdesk-frontend
  template:
    metadata:
      labels:
        app: rustdesk-frontend
    spec:
      containers:
        - name: frontend
          image: rustdesk-saas-frontend:latest
          imagePullPolicy: Never
