apiVersion: v1
kind: Service
metadata:
  name: hbbr
spec:
  type: ClusterIP
  selector:
    app: rustdesk-hbbr
  ports:
    - name: relay
      protocol: TCP
      port: 21117
      targetPort: 21117
    - name: web-relay
      protocol: TCP
      port: 21119
      targetPort: 21119